### ISSUE TITLE
Original todo list

### ISSUE THREAD

**Issue by nirizr** [nirizr/vss-ransom-restore#1]
- [ ] 32 & 64 bit single file
- [ ] output count is per drive. change to per run/execution of tool
- [ ] command line options to control restore file structure (override original file names, delete encrypted files, etc)
- [ ] change output format (to file? control verbosity better?)
- [ ] Don't override already restored files - optimization
